name: Build Zed

on:
  schedule:
    - cron: "36 18 * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: date
        name: Get date stamp for release
        run: "echo dateStamp=$(Get-Date -UFormat '%Y-%m-%d') >> $env:GITHUB_OUTPUT"
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fix Windows path length limit
        shell: powershell
        run: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
      - name: Download Rust installer
        run: Invoke-WebRequest https://static.rust-lang.org/dist/rust-1.85.1-x86_64-pc-windows-msvc.msi -OutFile C:\rustup.msi
      - name: Install Rust
        run: Start-Process msiexec.exe -Wait -ArgumentList '/i C:\rustup.msi /qb!'
      - name: Install VC++
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true
      - name: Install CMake
        uses: ssrobins/install-cmake@v1
      - name: Cache Cargo files
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build release
        shell: cmd
        run: |
          cd zed
          cargo run --release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.date.outputs.dateStamp }}"
          files: ./zed/target/release/zed.exe
